---
services:
  slaanesh:
    image: ghcr.io/h-quer/slaanesh:latest
    container_name: slaanesh
    restart: unless-stopped
    networks:
      - slaanesh
    volumes:
      - .:/files/config
      - import:/files/import
      - export:/files/export
      - covers:/files/covers
      - database:/files/database
      - downloads:/files/downloads
    ports:
      - 8428:8080

volumes:
  import:
  export:
  covers:
  database:
  downloads:

networks:
  slaanesh:
    driver: bridge

