---
services:
  slaanesh:
    image: ghcr.io/h-quer/slaanesh:latest
    container_name: slaanesh
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - your_config_dir:/files/config
      - your_import_dir:/files/import
      - your_export_dir:/files/export
      - your_covers_dir:/files/covers
      - your_database_dir:/files/database
      - your_downloads_dir:/files/downloads
    ports:
      - 8428:8080
